uzword = [
    'salom', 'kitob', 'daryo', 'oyna', 'oy', 'yil', 'kun', 'kecha', 'bugun', 'ertaga',
    'bola', 'qiz', 'yigit', 'ota', 'ona', 'aka', 'uka', 'singil', 'do‘st', 'o‘qituvchi',
    'maktab', 'bog‘cha', 'mehnat', 'uy', 'qo‘l', 'oyoqlar', 'boshlash', 'yakunlash', 'yurak', 'til',
    'so‘z', 'shahar', 'qishloq', 'dala', 'tosh', 'tog‘', 'daraxt', 'gul', 'qush', 'hayvon',
    'it', 'mushuk', 'sigir', 'ot', 'cho‘p', 'yomg‘ir', 'quyosh', 'oynash', 'qalam', 'qog‘oz',
    'dars', 'sinfdosh', 'yozish', 'o‘qish', 'eslatma', 'taom', 'non', 'suv', 'choy', 'shirinlik',
    'bozor', 'narx', 'pul', 'do‘kon', 'mashina', 'avtobus', 'poyezd', 'samolyot', 'yo‘l', 'ko‘cha',
    'doira', 'kvadrat', 'uchburchak', 'rang', 'oq', 'qora', 'qizil', 'yashil', 'ko‘k', 'sariq',
    'yengil', 'og‘ir', 'tez', 'sekin', 'katta', 'kichik', 'yangi', 'eski', 'qulay', 'noqulay',
    'baxt', 'quvonch', 'g‘am', 'dard', 'doim', 'hech', 'ba’zan', 'ko‘p', 'kam', 'ko‘z',
    'quloq', 'burun', 'og‘iz', 'soch', 'tish', 'qo‘shiq', 'raqam', 'raqamlar', 'raqamli', 'matematika',
    'fayz', 'inson', 'hayot', 'ta’lim', 'ilm', 'texnika', 'fan', 'tarix', 'madaniyat', 'san’at',
    'sport', 'sayohat', 'tinchlik', 'do‘stlik', 'mehr', 'mehribonlik', 'vaqt', 'fazilat', 'qadr', 'hurmat',
    'chiqish', 'kirish', 'ushlash', 'berish', 'olish', 'ko‘rish', 'eslash', 'o‘y', 'fikr', 'hissiyot',
    'orzu', 'umid', 'vatan', 'mamlakat', 'hudud', 'shaxs', 'jamiyat', 'qonun', 'yo‘l', 'yo‘riqnoma',
    'ish', 'ishchi', 'boshliq', 'rahbar', 'vakolat', 'mas’uliyat', 'yordam', 'quvvat', 'kuch', 'to‘p',
    'musobaqa', 'jamoa', 'raqib', 'g‘alaba', 'mag‘lubiyat', 'sabr', 'qat’iyat', 'muvaffaqiyat', 'xatolik', 
    'imkoniyat','baraka', 'xotira', 'esdalik', 'suhbat', 'muzokara', 'bitim', 'shartnoma', 'qaror', 'rejalar', 'maqsad','natija', 'tajriba',
    'ta’sir', 'yordamchi', 'doimiy', 'muntazam', 'tez-tez', 'ba’zan', 'hozir', 'keyin','oldin', 'yangi', 'qadimiy', 'mashhur', 
    'nodir', 'maxsus', 'oddiy', 'umumiy', 'shaxsiy', 'jamoaviy','qiziqarli', 'zerikarli', 'kutilgan', 'kutilmagan', 'to‘liq',
    'qisman', 'juda', 'kamdan-kam', 'hamisha', 'birinchi','oxirgi', 'o‘rta', 'boshqa', 'shu', 'bitta', 'ikki', 'uch', 'to‘rt', 'besh', 'olti',
    'yetti', 'sakkiz', 'to‘qqiz', 'o‘n', 'yigirma', 'o‘ttiz', 'qirq', 'ellik', 'oltmish', 'yetmish',
    'sakson', 'to‘qson', 'yuz', 'ming', 'million', 'milliard', 'trillion', 'sanash', 'hisoblash', 'raqamli',
    'matn', 'xabar', 'yangilik', 'maqola', 'kitobxona', 'jurnal', 'gazeta', 'sayt', 'internet', 'kompyuter',
    'dastur', 'ilova', 'o‘yin', 'film', 'kino', 'televizor', 'radio', 'muzika', 'konsert', 'teatr',
    'san’atkor', 'yozuvchi', 'shoir', 'tarjimon', 'tarixchi', 'oliy', 'maktab', 'universitet', 'fakultet', 'kurs',
    'imtihon', 'baholash', 'talaba', 'o‘qituvchi', 'o‘qish', 'yo‘nalish', 'kasb', 'ishlab chiqarish', 'sanoat', 'qishloq xo‘jaligi',
    'fermer', 'bog‘bon', 'hunar', 'san’at', 'mehnat', 'ishchi', 'boshqaruv', 'rahbar', 'mutaxassis', 'vakansiya',
    'ish o‘rni', 'maosh', 'bonus', 'rag‘bat', 'jarima', 'tashkilot', 'firma', 'korxona', 'kompaniya', 'bank',
    'moliyaviy', 'investitsiya', 'foyda', 'zarar', 'soliq', 'byudjet', 'tadbirkor', 'biznes', 'marketing', 'reklama',
    'sotish', 'savdo', 'mijoz', 'xizmat', 'savdo nuqtasi', 'bozor', 'mahsulot', 'xarid', 'sotib olish', 'yetkazib berish',
    'transport', 'avtomobil', 'velosiped', 'mototsikl', 'temir yo‘l', 'avtobus', 'metro', 'samolyot', 'kema', 'port',
    'uchish', 'qo‘nish', 'harakat', 'yo‘l harakati', 'trafik', 'qoidalar', 'jarayon', 'holat', 'vaziyat', 'muammo',
    'yechim', 'yordam', 'tashabbus', 'taklif', 'muzokara', 'bitim', 'shartnoma', 'loyiha', 'investor', 'partner',
    'hamkorlik', 'tarmoq', 'aloqa', 'telefon', 'mobil', 'internet', 'tarmoqli', 'platforma', 'dasturiy ta’minot', 'ma’lumot',
    'bazasi', 'tahlil', 'statistika', 'hisobot', 'ko‘rsatkich', 'indikator', 'rejalar', 'strategiya', 'maqsad', 'vazifa',
    'ijro', 'nazorat', 'baholash', 'moliya', 'buxgalteriya', 'audit', 'soliq', 'foyda', 'zarar', 'daromad',
    'xarajat', 'byudjet', 'resurs', 'inson kapitali', 'mehnat bozori', 'kasb', 'hunar', 'malaka', 'ta’lim', 'kadrlar',
    'ijtimoiy', 'siyosiy', 'iqtisodiy', 'madaniy', 'texnologik', 'innovatsiya', 'loyiha', 'startap', 'investitsiya', 'risk',
    'barqarorlik', 'o‘sish', 'taraqqiyot', 'bozor', 'savdo', 'tadbirkorlik', 'korxona', 'kompaniya', 'firma', 'brend',
    'marketing', 'reklama', 'sotuv', 'xaridor', 'mijoz', 'xizmat', 'logistika', 'yetkazib berish', 'ombor', 'inventarizatsiya',
    'sifat', 'texnika', 'xavfsizlik', 'mehnat muhofazasi', 'hujjat', 'shartnoma', 'qonun', 'qoidalar', 'norma', 'me’yor',
    'jarayon', 'vazifa', 'majburiyat', 'javobgarlik', 'tashkilot', 'boshqaruv', 'rahbar', 'mutaxassis', 'xodim', 'jamoa',
    'muloqot', 'jurnal', 'gazeta', 'internet sayti', 'axborot', 'yangilik', 'resurs', 'kutubxona', 'ilmiy', 'tadqiqot',
    'ma’lumotnoma', 'dokument', 'tadbirkor', 'sarmoya', 'foyda', 'zarar', 'soliq', 'moliya', 'byudjet', 'bank',
    'kredit', 'foiz', 'investitsiya', 'bozor', 'aksiyalar', 'fond', 'fond birjasi', 'iqtisodiyot', 'sanoat', 'qishloq xo‘jaligi',
    'transport', 'aloqa', 'turizm', 'ta’lim', 'madaniyat', 'san’at', 'sport', 'axborot texnologiyalari', 'internet', 'mobil aloqa',
    'kompyuter', 'dastur', 'ilova', 'o‘yin', 'film', 'kino', 'televizor', 'radio', 'gazeta', 'jurnal',
    'kitob', 'ma’lumot', 'ilm', 'ta’lim', 'tarbiya', 'inson', 'jamiyat', 'xalq', 'davlat', 'hudud',
    'shahar', 'qishloq', 'viloyat', 'tuman', 'mahalla', 'qo‘shni', 'do‘st', 'oilaviy', 'ijtimoiy', 'madaniy',
    'an’analar', 'bayram', 'tadbir', 'marosim', 'jamoa', 'ijtimoiy tarmoqlar', 'aloqa', 'muloqot', 'rahbar', 'boshqaruv',
    'mas’uliyat', 'ijtimoiy himoya', 'sog‘liq', 'tibbiyot', 'dorixona', 'kasalxona', 'dorilar', 'profilaktika', 'davolash', 'ta’sir',
    'ekologiya', 'atrof-muhit', 'tabiat', 'hayvonot', 'o‘simliklar', 'biologiya', 'kimyo', 'fizika', 'matematika', 'geografiya',
    'tarix', 'adabiyot', 'san’at', 'musiqa', 'teatr', 'kino', 'sport', 'jismoniy tarbiya', 'o‘yin', 'mashg‘ulot',
    'marafon', 'musobaqa', 'yutuq', 'g‘alaba', 'mag‘lubiyat', 'sabr', 'qat’iyat', 'mehnat', 'dam olish', 'sayohat',
    'turar joy', 'uy', 'xona', 'oshxona', 'yotoqxona', 'mehmonxona', 'bog‘', 'ko‘cha', 'maydon', 'park',
    'bog‘cha', 'maktab', 'universitet', 'kutubxona', 'muzey', 'galereya', 'teatr', 'stadion', 'binosi', 'inshoot',
    'ko‘prik', 'yo‘l', 'transport', 'avtomobil', 'velosiped', 'mototsikl', 'avtobus', 'metropoliten', 'samolyot', 'kema',
    'port', 'terminal', 'stansiya', 'binolar', 'infratuzilma', 'kommunal', 'servis', 'xizmat', 'energiya', 'gaz',
    'elektr', 'suv', 'issiq suv', 'issiqlik', 'ventilyatsiya', 'konditsioner', 'texnika', 'telefon', 'kompyuter', 'internet',
    'dasturiy ta’minot', 'mobil ilova', 'o‘yin', 'multfilm', 'kitob', 'maqola', 'maqolalar', 'yangiliklar', 'tadbirlar', 'loyiha',
    'tadbirkorlik', 'biznes', 'marketing', 'reklama', 'savdo', 'sotuv', 'xarid', 'mijoz', 'xizmat', 'moliya',
    'bank', 'kredit', 'investitsiya', 'foyda', 'zarar', 'byudjet', 'soliq', 'audit', 'hisobot', 'rejalar',
    'strategiya', 'tahlil', 'statistika', 'indikator', 'vazifa', 'majburiyat', 'javobgarlik', 'rahbar', 'xodim', 'jamoa',
    'muloqot', 'suhbat', 'muzokara', 'bitim', 'shartnoma', 'loyiha', 'tashabbus', 'taklif', 'ijro', 'nazorat',
]
